name: Microblog Post
description: Create a micro-blog entry
title: "[microblog] "
labels: ["microblog"]
body:
  - type: markdown
    attributes:
      value: |
        Quick post. Keep it simple.

  - type: textarea
    id: content
    attributes:
      label: Content
      description: Your post content (markdown supported)
    validations:
      required: true

  - type: input
    id: kind
    attributes:
      label: Kind
      description: Post type
      placeholder: note, link, thought, code
      value: note

  - type: input
    id: tags
    attributes:
      label: Tags
      description: Comma-separated tags
      placeholder: ruby, climbing, alaska
