"h.h. the 14th dalai lama" :
- |
  be kind whenever possible.  it is always possible.

"arthur schopenhauer" :
- |
  the world is everything that is the case
- |
  talent hits a target no one else can hit; genius hits a target no one else can see
- |
  life is a constant process of dying
- |
  compassion is the basis of morality
- |
  a man can do what he wills, but he cannot will what he wills
- |
  we forfeit three-fourths of ourselves in order to be like other people
- |
  every man takes the limits of his own field of vision for the limits of the world
- |
  the two enemies of human happiness are pain and boredom
- |
  the first forty years of life give us the text; the next thirty supply the commentary on it
- |
  great men are like eagles, and build their nest on some lofty solitude
