#! /usr/bin/env ruby
#  encoding: utf-8

script do
  tldr <<~____
    ~> translate uk
  ____

  run do
    lang = argv.shift

  end
end

BEGIN {
  require_relative '../lib/script.rb'
  require_relative '../lib/boot.rb'

  def site
    Site.only
  end

  Dir.chdir(File.dirname(__dir__))
}
